<!DOCTYPE html>
<html>
<head>
    <title>Solutions Project Euler</title>
    <link rel="stylesheet" type="text/css" href="../css/main.css" />
</head>
<body>

<h1>Even Fibonacci numbers</h1>
<h2>Problem 2</h2>
<div class = "paragraphGrouping">
    <p>Each new term in the Fibonacci sequence is generated by adding the previous
        two terms. By starting with 1 and 2, the first 10 terms will be:</p>

    <p>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>

    <p>By considering the terms in the Fibonacci sequence whose values do not
        exceed four million, find the sum of the even-valued terms.</p>

    <?php
    $time = microtime(1);
    $num1 = 1; $num2 = 2; $total = 0; $total2 = 2; $counter = 3;
    while($num2 < 4000000){
        //echo $num1 . ' + ' . $num2 . ' = ';
        $total = $num1 + $num2;
        $num1 = $num2;
        $num2 = $total;

        //echo $total . " ";

        //if ($counter >= 20 && $counter <= 40){
            //echo $counter++ . " = " . $total . "<br>";
        //}

        if ($num2 % 2 === 0){
            //echo $num2 . " ";
            $total2 += $num2;
            /* ?> <p></p> <?php */
        }
    }
    echo "Total: " . $total2 . " Time: " . (microtime(1) - $time) . "<br>";
    ?>

    <?php
    $time = microtime(1);
    //an = [ Phin - (phi)n ]/Sqrt[5].
    //Phi=(1+Sqrt[5])/2
    //phi=(1-Sqrt[5])/2

    $Phi    = ((1 + sqrt(5))/2);
    $phi    = ((1 - sqrt(5))/2);
    $total  = 0;
    $total2 = 0;
    $i = -1;

    while ($total < 4000000){
        $i++;
        $total = round((pow($Phi, $i) - (pow($phi, $i))) / sqrt(5));

        //if ($i >= 20 && $i <= 40){
            //echo $i . " = " . $total . "<br>";
        //}

        if ($total % 2 === 0){
            $total2 += $total;
            //echo "Total: " . $total . " Total 2: " . $total2 . " ";
            //echo $total2. " ";
        }
    }

    echo "Total: " . $total2 . " Time: " . (microtime(1) - $time) . "<br>";
    ?>
    <?php
    function Fib($n){
        return round((pow(((1 + sqrt(5))/2), $n) - (pow(((1 - sqrt(5))/2), $n))) / sqrt(5));
    }



    $time = microtime(1);
    Fib(57);
    echo "Time: " . (microtime(1) - $time);
    ?>
</div>
</body>
</html>